### PR TITLE
feat(breaking): Bump the required Node.js version to v18.19.0 (LTS)

### PR DESCRIPTION
**Pull request by thewilloftheshadow**
Supercedes #119

### CODE REVIEW

**Comment by OIRNOIR** [comment]
Why do tests fail

**Comment by OIRNOIR** [comment]
Oh out of date lockfile

**Comment by OIRNOIR** [comment]
Aaaand the tests use node v16

**Comment by OIRNOIR** [comment]
Don't merge this yet

**Review by OIRNOIR — APPROVED** [review]
Works for me now that I've fixed it

**Comment by OIRNOIR** [comment]
Also, v18.19.0 is not lts, v20 is lts

**Comment by thewilloftheshadow** [comment]
> Also, v18.19.0 is not lts, v20 is lts

I meant the LTS version of v18

**Pull request merged**
