### PR TITLE
Kiai.js v1

### PR DESCRIPTION
**Pull request by thewilloftheshadow**

### CODE REVIEW

**Review by OIRNOIR — APPROVED** [review]
I'm not really sure if all of this is correct (this is a huge diff) but looking through the various features and stuff there doesn't seem to be anything I'd want to change

**Comment by thewilloftheshadow** [comment]
That's fine, I'll go through and do full tests, as long as you like the structure

**Comment by OIRNOIR** [comment]
Yeah, the structure lgtm

**Comment by OIRNOIR** [comment]
But fix the failed build

**Pull request merged**
